table _Measures
	lineageTag: 8f2b6e5a-1c4d-4a3e-9f7b-2d6e8a0c5b1f

	measure 'Total Events' = 411709736
		formatString: #,##0
		displayFolder: 'Overview KPIs'

	measure 'Purchasing Users' = 2064899
		formatString: #,##0
		displayFolder: 'Overview KPIs'

	measure 'Overall Conversion Rate' = 0.0609
		formatString: 0.00%
		displayFolder: 'Overview KPIs'

	measure 'Total Revenue' = 2060000000
		formatString: "$"#,##0
		displayFolder: 'Overview KPIs'

	measure 'Cart Abandonment Rate' = 0.5409
		formatString: 0.00%
		displayFolder: 'Overview KPIs'

	measure 'Champion Revenue Share' = CALCULATE(SUM(FactRFMSegment[PctRevenue]), FactRFMSegment[Segment] = "Champion")
		formatString: 0.00%
		displayFolder: 'Overview KPIs'

	measure 'Month-1 Retention Avg' = CALCULATE(SUM(FactRetentionCurve[AvgRetention]), FactRetentionCurve[MonthsSinceFirst] = "M1")
		formatString: 0.00%
		displayFolder: 'Overview KPIs'

	measure 'COVID Session Conversion Lift' = VAR PreValue = CALCULATE(SUM(FactCovidComparison[PreCovid]), FactCovidComparison[Metric] = "Session Conversion %") VAR OnsetValue = CALCULATE(SUM(FactCovidComparison[CovidOnset]), FactCovidComparison[Metric] = "Session Conversion %") RETURN DIVIDE(OnsetValue - PreValue, PreValue)
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: 'Overview KPIs'

	partition _Measures = calculated
		mode: import
		source = {1}

	annotation PBI_Id = 6a3f8e2d4c1b4f9a8e7d2c5b1a0f3e6d

