table _Measures
	lineageTag: 8f2b6e5a-1c4d-4a3e-9f7b-2d6e8a0c5b1f

	measure 'Total Events' = 411709736
		formatString: #,##0
		displayFolder: 'Overview KPIs'
		description: Total events logged in the REES46 dataset, Oct 2019 - Apr 2020 (verified row count from BigQuery load). Fixed constant - no raw event-count table is imported into this model, since Import mode uses only pre-aggregated per-module summaries.

	measure 'Purchasing Users' = 2064899
		formatString: #,##0
		displayFolder: 'Overview KPIs'
		description: Distinct users with at least one purchase event (Module 3, RFM base query). Fixed constant - user-level granularity is not imported into this model.

	measure 'Overall Conversion Rate' = 0.0609
		formatString: 0.00%
		displayFolder: 'Overview KPIs'
		description: View-to-purchase conversion rate across the full dataset, all 14 categories (Module 1, Query 1). Fixed constant, not computed live from FactFunnelByCategory - that table holds only the top 10 of 14 categories shown in the Excel workbook, so summing it would silently undercount and drift from the verified 6.09%.

	measure 'Total Revenue' = 2060000000
		formatString: "$"#,##0.00,,,"B"
		displayFolder: 'Overview KPIs'
		description: Total platform revenue across all 14 categories, in USD (Module 5). Fixed constant - FactCategoryPerformance holds only 8 of 14 categories, so summing it would silently undercount.

	measure 'Cart Abandonment Rate' = 0.5409
		formatString: 0.00%
		displayFolder: 'Overview KPIs'
		description: Share of cart sessions that never converted to a purchase, full dataset (Module 1, Query 3). Fixed constant for the same reason as Overall Conversion Rate.

	measure 'Champion Revenue Share' = CALCULATE(SUM(FactRFMSegment[PctRevenue]), FactRFMSegment[Segment] = "Champion")
		formatString: 0.00%
		displayFolder: 'Overview KPIs'
		description: Share of total revenue generated by the Champion RFM segment. Live measure - FactRFMSegment is exhaustive (covers all 6 segments), so this recalculates correctly from the model rather than needing a fixed constant.

	measure 'Month-1 Retention Avg' = CALCULATE(SUM(FactRetentionCurve[AvgRetention]), FactRetentionCurve[MonthsSinceFirst] = "M1")
		formatString: 0.00%
		displayFolder: 'Overview KPIs'
		description: Average retention rate one month after first purchase, across all 7 cohorts. Live measure from the exhaustive FactRetentionCurve table.

	measure 'COVID Session Conversion Lift' = VAR PreValue = CALCULATE(SUM(FactCovidComparison[PreCovid]), FactCovidComparison[Metric] = "Session Conversion %") VAR OnsetValue = CALCULATE(SUM(FactCovidComparison[CovidOnset]), FactCovidComparison[Metric] = "Session Conversion %") RETURN DIVIDE(OnsetValue - PreValue, PreValue)
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: 'Overview KPIs'
		description: Relative change in session-level conversion rate from the pre-COVID baseline to the COVID onset period. Live measure from the exhaustive FactCovidComparison table.

	partition _Measures = calculated
		mode: import
		source = {1}

	annotation PBI_Id = 6a3f8e2d4c1b4f9a8e7d2c5b1a0f3e6d

