table _Measures
	lineageTag: 8f2b6e5a-1c4d-4a3e-9f7b-2d6e8a0c5b1f

	/// Every view, cart add, and purchase tracked across the full October 2019-April 2020 period - the complete activity behind everything else on this page. This is a fixed snapshot number rather than something that recalculates as you filter, since it reflects the whole dataset, not one slice of it.
	measure 'Total Events' = 411709736
		formatString: #,##0
		displayFolder: 'Overview KPIs'
		lineageTag: f40b8719-ee36-452f-99c1-5a7113673ff8

	/// The number of distinct customers who bought at least once during the tracked period. Like Total Events, this is a fixed snapshot number rather than something that recalculates as you filter.
	measure 'Purchasing Users' = 2064899
		formatString: #,##0
		displayFolder: 'Overview KPIs'
		lineageTag: d6a46e5e-244e-4231-8482-fd7b3c35ad64

	/// The share of all product views, across every category in the dataset, that ended in a purchase. This is a fixed snapshot number covering the full category set - it won't match a number you might calculate from just the categories shown elsewhere on this page, since those only cover the top performers.
	measure 'Overall Conversion Rate' = 0.0609
		formatString: 0.0%
		displayFolder: 'Overview KPIs'
		lineageTag: 85658db1-2ce6-48eb-8965-e2649a28847b

		annotation PBI_FormatHint = {"isCustom":true}

	/// Total purchase revenue across every category in the dataset, in US dollars. Like Overall Conversion Rate, this is a fixed snapshot covering the full category set, not just the categories shown elsewhere on this page.
	measure 'Total Revenue' = 2060000000
		formatString: "$"#,##0
		displayFolder: 'Overview KPIs'
		lineageTag: 14a1b683-6977-4e98-87e6-c7c9010d0595

	/// The share of shopping-cart sessions that never turned into a purchase. A fixed snapshot number for the full tracked period.
	measure 'Cart Abandonment Rate' = 0.5409
		formatString: 0.0%
		displayFolder: 'Overview KPIs'
		lineageTag: 75a7afe1-ecc7-4e7d-9e34-e1668d620cd1

		annotation PBI_FormatHint = {"isCustom":true}

	/// The share of total revenue that comes from Champions - the highest-value customer segment (most recent, most frequent, and highest-spending). This number updates automatically if the underlying customer data changes, since it's calculated from all 6 segments directly.
	measure 'Champion Revenue Share' = CALCULATE(SUM(FactRFMSegment[PctRevenue]), FactRFMSegment[Segment] = "Champion")
		formatString: 0.0%
		displayFolder: 'Overview KPIs'
		lineageTag: 5a198fd3-390d-4041-bd75-d128789c330c

		annotation PBI_FormatHint = {"isCustom":true}

	/// The average share of customers who came back to purchase again in their second calendar month, across every acquisition cohort. Updates automatically as new cohort data comes in.
	measure 'Month-1 Retention Avg' = CALCULATE(SUM(FactRetentionCurve[AvgRetention]), FactRetentionCurve[MonthsSinceFirst] = "M1")
		formatString: 0.00%
		displayFolder: 'Overview KPIs'
		lineageTag: d70921b5-9452-40d9-83ad-443a9e525873

	/// How much conversion rate changed after COVID-19 lockdowns began, compared to right before. A positive number means more sessions converted after onset than before. Updates automatically if the underlying comparison data changes.
	measure 'COVID Session Conversion Lift' = VAR PreValue = CALCULATE(SUM(FactCovidComparison[PreCovid]), FactCovidComparison[Metric] = "Session Conversion %") VAR OnsetValue = CALCULATE(SUM(FactCovidComparison[CovidOnset]), FactCovidComparison[Metric] = "Session Conversion %") RETURN DIVIDE(OnsetValue - PreValue, PreValue)
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: 'Overview KPIs'
		lineageTag: 7aad4945-6362-4370-9e07-6ba017a7676e

	/// Hex color code (green or red) reflecting whether the COVID Session Conversion Lift measure is positive or negative. Feeds the badge background on the 'COVID Lift KPI Card' HTML Content visual - not meant to be used directly in a chart.
	measure 'COVID Lift Color' = IF ( [COVID Session Conversion Lift] >= 0, "#2ECC71", "#E74C3C" )
		displayFolder: HTML Cards
		lineageTag: 3c30c61a-a086-4895-98e9-a4232732d3b4

	/// Plain-language read of whether conversion improved or declined after COVID-19 onset, driven by the sign of COVID Session Conversion Lift. Feeds the 'COVID Lift KPI Card' HTML Content visual - not meant to be used directly in a chart.
	measure 'COVID Lift Direction Text' =
			IF (
			    [COVID Session Conversion Lift] >= 0,
			    "Conversion rate improved after COVID-19 onset",
			    "Conversion rate declined after COVID-19 onset"
			)
		displayFolder: HTML Cards
		lineageTag: fd3ca5f4-1b97-4b54-99f5-d13da1bdc822

	/// Self-contained HTML/CSS string combining the COVID Session Conversion Lift value, a color-coded badge, and a plain-language interpretation - built for the HTML Content custom visual, which renders whatever HTML a bound measure returns. Demonstrates a compound KPI card a native Power BI card visual can't produce in a single tile. Bind this measure to the visual's data role.
	measure 'COVID Lift KPI Card' =
			VAR LiftValue = FORMAT ( [COVID Session Conversion Lift], "+0.0%;-0.0%;0.0%" )
			VAR BadgeColor = [COVID Lift Color]
			VAR DirectionText = [COVID Lift Direction Text]
			RETURN
			    "<div style='font-family:Segoe UI,sans-serif;text-align:center;padding:12px;'>" &
			        "<div style='font-size:12px;color:#9B9BA8;text-transform:uppercase;letter-spacing:0.5px;'>COVID Impact on Conversion</div>" &
			        "<div style='font-size:32px;font-weight:700;color:#FFFFFF;margin-top:4px;'>" & LiftValue & "</div>" &
			        "<div style='display:inline-block;margin-top:8px;padding:4px 12px;border-radius:12px;font-size:12px;font-weight:400;color:black;background-color:" & BadgeColor & ";'>" & DirectionText & "</div>" &
			    "</div>"
		displayFolder: HTML Cards
		lineageTag: e56ed8dc-76de-4659-9d04-7156ddab4b5d

	/// Where the current Month-1 Retention Avg sits between the lowest and highest single-cohort M1 retention on record (0 = at the historical low, 1 = at the historical high). Feeds the badge on the 'Month-1 Retention KPI Card' - not meant to be used directly in a chart.
	measure 'Retention Position Ratio' =
			VAR M1Avg = [Month-1 Retention Avg]
			VAR M1Min = CALCULATE(SUM(FactRetentionCurve[MinRetention]), FactRetentionCurve[MonthsSinceFirst] = "M1")
			VAR M1Max = CALCULATE(SUM(FactRetentionCurve[MaxRetention]), FactRetentionCurve[MonthsSinceFirst] = "M1")
			RETURN DIVIDE(M1Avg - M1Min, M1Max - M1Min)
		displayFolder: HTML Cards
		lineageTag: deca8e6b-02b5-4b6d-a417-735ac0af1347

	/// Plain-language read of where the current Month-1 Retention Avg sits relative to the historical range of individual cohorts, based on Retention Position Ratio. Feeds the 'Month-1 Retention KPI Card' - not meant to be used directly in a chart.
	measure 'Retention Position Text' =
			VAR Ratio = [Retention Position Ratio]
			RETURN
			    SWITCH(
			        TierBucket(Ratio),
			        "Low", "Toward the lower end of the historical cohort range",
			        "High", "Toward the higher end of the historical cohort range",
			        "In the middle of the historical cohort range"
			    )
		displayFolder: HTML Cards
		lineageTag: adc6ce70-bef6-4b0b-a4c5-fcb55e0338b1

	/// Hex color code (amber/blue/green) reflecting whether the current Month-1 Retention Avg sits in the lower, middle, or upper third of the historical cohort range. Feeds the badge background on the 'Month-1 Retention KPI Card' - not meant to be used directly in a chart.
	measure 'Retention Position Color' =
			VAR Ratio = [Retention Position Ratio]
			RETURN
			    SWITCH(
			        TierBucket(Ratio),
			        "Low", "#E67E22",
			        "High", "#2ECC71",
			        "#5B8DBE"
			    )
		displayFolder: HTML Cards
		lineageTag: 4151cde0-9079-4246-baa9-659ce86836d3

	/// Self-contained HTML/CSS string combining the Month-1 Retention Avg value with a badge showing where it sits relative to the historical range of individual cohorts (min-max from FactRetentionCurve) - not an external benchmark, purely this dataset's own cohort history. Bind this measure to an HTML Content visual's data role.
	measure 'Month-1 Retention KPI Card' =
			VAR RetentionValue = FORMAT ( [Month-1 Retention Avg], "0.0%" )
			VAR BadgeColor = [Retention Position Color]
			VAR PositionText = [Retention Position Text]
			RETURN
			    "<div style='font-family:Segoe UI,sans-serif;text-align:center;padding:12px;'>" &
			        "<div style='font-size:12px;color:#9B9BA8;text-transform:uppercase;letter-spacing:0.5px;'>Month-1 Retention Avg</div>" &
			        "<div style='font-size:32px;font-weight:700;color:#FFFFFF;margin-top:4px;'>" & RetentionValue & "</div>" &
			        "<div style='display:inline-block;margin-top:8px;padding:4px 12px;border-radius:12px;font-size:12px;font-weight:400;color:black;background-color:" & BadgeColor & ";'>" & PositionText & "</div>" &
			    "</div>"
		displayFolder: HTML Cards
		lineageTag: e9cf188e-6674-4aee-9dc7-6ea8e5c46f75

	/// Single dynamic sentence synthesizing the Overview page's core story - conversion rate, cart abandonment, and month-1 retention - recalculated live from the model so it never goes stale if someone filters the page differently. Not a static caption; reuses the Retention Position Ratio logic already built for the retention KPI card. Bind directly to a text-based visual (Card, HTML Content, or a text box referencing this measure).
	measure 'Overview Insight' =
			VAR ConvRate = FORMAT ( [Overall Conversion Rate], "0.0%" )
			VAR AbandonRate = FORMAT ( [Cart Abandonment Rate], "0.0%" )
			VAR RetentionRate = FORMAT ( [Month-1 Retention Avg], "0.0%" )
			VAR Ratio = [Retention Position Ratio]
			VAR RetentionFraming =
			    SWITCH(
			        TierBucket(Ratio),
			        "Low", "toward the weaker end of the historical range",
			        "High", "toward the stronger end of the historical range",
			        "roughly mid-range historically"
			    )
			VAR InsightText = ConvRate & " of views convert and " & AbandonRate & " of carts are abandoned; first-month retention lands at " & RetentionRate & ", " & RetentionFraming & "."
			RETURN
			    "<div style='font-family:""Segoe UI Light"",""Segoe UI"",sans-serif;font-weight:300;color:#FFFFFF;font-size:20px;'>" & InsightText & "</div>"
		displayFolder: Insights\Overview
		lineageTag: 709af52b-ac37-4ed3-807f-9eb8ac924e30

	/// Single dynamic sentence comparing how strongly session depth, category, and brand each swing conversion rate - recalculates live so the multiples always match current data. Also dynamically checks whichever category currently ranks #1 by conversion against the TaxonomyMislabeledFlag column, only appending the taxonomy caveat if the actual top-ranked category is the flagged one (does not hardcode a category name). Bind to an HTML Content visual's data role.
	measure 'Funnel Insight' =
			VAR TopCategoryTable =
			    TOPN(1, SUMMARIZE(FactFunnelByCategory, FactFunnelByCategory[CategoryCode], "CatRate", [Category Conversion Rate]), [CatRate], DESC)
			VAR TopCategoryCode = MAXX(TopCategoryTable, FactFunnelByCategory[CategoryCode])
			VAR TopCategoryDisplayName = LOOKUPVALUE(DimCategory[DisplayName], DimCategory[CategoryCode], TopCategoryCode)
			VAR TopCategoryFlagged = LOOKUPVALUE(DimCategory[TaxonomyMislabeledFlag], DimCategory[CategoryCode], TopCategoryCode)
			VAR SessionMin = MINX(VALUES(FactSessionDepth[EventBucket]), [Session Conversion Rate])
			VAR SessionMax = MAXX(VALUES(FactSessionDepth[EventBucket]), [Session Conversion Rate])
			VAR SessionSwing = FORMAT(DIVIDE(SessionMax, SessionMin), "0")
			VAR MainParagraph =
			    "How much someone browses matters far more than what they browse. Visitors who view just one product almost never buy, but conversion climbs sharply the more they look around, leveling off once someone's clearly engaged - a swing of roughly " & SessionSwing & "x between the least and most engaged visitors, dwarfing anything category or brand choice can explain."
			VAR CaveatParagraph =
			    IF(
			        TopCategoryFlagged = "Y",
			        "<p style='margin:8px 0 0 0;'>Note: the top category shown, " & TopCategoryDisplayName & ", has a known data quality flag - see Data Quality Findings for details. More detail is available on the Category & Brand page.</p>",
			        ""
			    )
			RETURN
			    "<div style='font-family:""Segoe UI Light"",""Segoe UI"",sans-serif;font-weight:300;color:#FFFFFF;font-size:15px;text-align:justify;'><p style='margin:0;'>" & MainParagraph & "</p>" & CaveatParagraph & "</div>"
		displayFolder: Insights\Funnel
		lineageTag: 7e44e649-7356-471c-8c8f-cc7ad0f3ca6a

	/// Single dynamic paragraph summarizing revenue concentration across categories and brands - which category and which brand actually dominate revenue on this page, expressed as a share of total. Dynamically checks whichever category currently ranks #1 by revenue against the TaxonomyMislabeledFlag column, only appending the caveat if the actual top-ranked category is the flagged one. Bind to an HTML Content visual's data role.
	measure 'Category Brand Insight' =
			VAR TopCategoryTable =
			    TOPN(1, SUMMARIZE(FactCategoryPerformance, FactCategoryPerformance[CategoryCode], "Rev", CALCULATE(SUM(FactCategoryPerformance[TotalRevenue]))), [Rev], DESC)
			VAR TopCategoryCode = MAXX(TopCategoryTable, FactCategoryPerformance[CategoryCode])
			VAR TopCategoryRevenue = MAXX(TopCategoryTable, [Rev])
			VAR TopCategoryDisplayName = LOOKUPVALUE(DimCategory[DisplayName], DimCategory[CategoryCode], TopCategoryCode)
			VAR TopCategoryFlagged = LOOKUPVALUE(DimCategory[TaxonomyMislabeledFlag], DimCategory[CategoryCode], TopCategoryCode)
			VAR TotalCategoryRevenue = SUM(FactCategoryPerformance[TotalRevenue])
			VAR CategoryShare = FORMAT(DIVIDE(TopCategoryRevenue, TotalCategoryRevenue), "0%")
			VAR TopBrandTable =
			    TOPN(1, SUMMARIZE(FactTopBrands, FactTopBrands[Brand], "Rev", CALCULATE(SUM(FactTopBrands[TotalRevenue]))), [Rev], DESC)
			VAR TopBrandName = MAXX(TopBrandTable, FactTopBrands[Brand])
			VAR TopBrandRevenue = MAXX(TopBrandTable, [Rev])
			VAR TotalBrandRevenue = SUM(FactTopBrands[TotalRevenue])
			VAR BrandShare = FORMAT(DIVIDE(TopBrandRevenue, TotalBrandRevenue), "0%")
			VAR TopBrandDisplayName = UPPER(LEFT(TopBrandName, 1)) & MID(TopBrandName, 2, LEN(TopBrandName))
			VAR MainParagraph =
			    IF(
			        TopCategoryFlagged = "Y",
			        "<p style='margin:0;font-weight:600;color:#E67E22;'>On the surface, " & TopCategoryDisplayName & " looks like it drives " & CategoryShare & " of all category revenue here - but that is an illusion: since December 2019, Apple/Samsung/Xiaomi products were reclassified into this category from Electronics, so it is really consumer electronics revenue hiding under the wrong label.</p>" &
			        "<p style='margin:8px 0 0 0;'>Strip that out, and the real concentration story is on the brand side: " & TopBrandDisplayName & " alone accounts for " & BrandShare & " of brand revenue shown here - more than every other brand combined.</p>",
			        "<p style='margin:0;'>" & TopCategoryDisplayName & " alone accounts for " & CategoryShare & " of the category revenue shown here, and " & TopBrandDisplayName & " a similar " & BrandShare & " of brand revenue - a handful of players carry most of the weight on this page, not a broad spread across categories or brands.</p>"
			    )
			RETURN
			    "<div style='font-family:""Segoe UI Light"",""Segoe UI"",sans-serif;font-weight:300;color:#FFFFFF;font-size:13px;text-align:justify;'>" & MainParagraph & "</div>"
		displayFolder: Insights\Category & Brand
		lineageTag: a64934ed-8a48-4e36-9a0a-960172c018ae

	/// Single dynamic insight for the Customer Segments page - dynamically finds whichever RFM segment currently ranks #1 by revenue share and contrasts its user share vs revenue share, then pairs it with the converting-vs-non-converting session behavior gap from FactConvertingVsNon. Bind to an HTML Content visual's data role.
	measure 'Customer Segments Insight' =
			VAR TopSegmentTable =
			    TOPN(1, SUMMARIZE(FactRFMSegment, FactRFMSegment[Segment], "Rev", CALCULATE(SUM(FactRFMSegment[PctRevenue]))), [Rev], DESC)
			VAR TopSegmentName = MAXX(TopSegmentTable, FactRFMSegment[Segment])
			VAR TopSegmentRevShare = MAXX(TopSegmentTable, [Rev])
			VAR TopSegmentUserShare = CALCULATE(SUM(FactRFMSegment[PctUsers]), FactRFMSegment[Segment] = TopSegmentName)
			VAR RevMultiple = FORMAT(DIVIDE(TopSegmentRevShare, TopSegmentUserShare), "0.0")
			VAR RevSharePct = FORMAT(TopSegmentRevShare, "0%")
			VAR UserSharePct = FORMAT(TopSegmentUserShare, "0%")
			VAR ConvEvents = CALCULATE(AVERAGE(FactConvertingVsNon[AvgEvents]), FactConvertingVsNon[SessionType] = "Converting")
			VAR NonConvEvents = CALCULATE(AVERAGE(FactConvertingVsNon[AvgEvents]), FactConvertingVsNon[SessionType] = "Non-Converting")
			VAR ConvCarts = CALCULATE(AVERAGE(FactConvertingVsNon[AvgCarts]), FactConvertingVsNon[SessionType] = "Converting")
			VAR MainParagraph = TopSegmentName & " customers are just " & UserSharePct & " of the base but generate " & RevSharePct & " of all revenue - " & RevMultiple & "x their fair share, and the clearest signal for where retention effort should concentrate."
			VAR SecondaryParagraph = "The same gap shows up in behavior: a converting session averages " & FORMAT(ConvEvents, "0.0") & " events and " & FORMAT(ConvCarts, "0.0") & " cart-adds, versus " & FORMAT(NonConvEvents, "0.0") & " events and barely any cart activity for one that does not - buyers engage differently, not just longer."
			RETURN
			    "<div style='font-family:""Segoe UI Light"",""Segoe UI"",sans-serif;font-weight:300;color:#FFFFFF;font-size:15px;text-align:justify;'><p style='margin:0;'>" & MainParagraph & "</p><p style='margin:8px 0 0 0;'>" & SecondaryParagraph & "</p></div>"
		displayFolder: Insights\Customer Segments
		lineageTag: ba20ed7c-59ca-4ba0-8db1-78e7a5853170

	/// Single dynamic insight for the COVID Impact page - recalculates live from FactCovidComparison. Complements the COVID Lift KPI Card (which headlines the session conversion number) by explaining the behavioral mechanism: deeper browsing (events/session, products viewed both up) alongside cheaper baskets (AOV down). Bind to an HTML Content visual's data role.
	measure 'COVID Impact Insight' =
			VAR EventsChangePct = CALCULATE(SUM(FactCovidComparison[ChangeText]), FactCovidComparison[Metric] = "Avg Events / Session")
			VAR ProductsChangePct = CALCULATE(SUM(FactCovidComparison[ChangeText]), FactCovidComparison[Metric] = "Avg Products Viewed")
			VAR AOVChangePct = CALCULATE(SUM(FactCovidComparison[ChangeText]), FactCovidComparison[Metric] = "Avg Order Value ($)")
			VAR EventsChangeText = FORMAT(EventsChangePct, "+0%;-0%;0%")
			VAR ProductsChangeText = FORMAT(ProductsChangePct, "+0%;-0%;0%")
			VAR AOVChangeText = FORMAT(AOVChangePct, "+0%;-0%;0%")
			VAR MainParagraph = "Lockdown did not just push more sessions toward a purchase - it changed how people shopped. Events per session rose " & EventsChangeText & " and products viewed rose " & ProductsChangeText & ", meaning visitors browsed noticeably deeper before deciding."
			VAR SecondaryParagraph = "But baskets got cheaper: average order value fell " & AOVChangeText & ". More people bought, and they browsed more to get there, but each purchase was worth less - consistent with buyers trading down during economic uncertainty."
			RETURN
			    "<div style='font-family:""Segoe UI Light"",""Segoe UI"",sans-serif;font-weight:300;color:#FFFFFF;font-size:15px;text-align:justify;'><p style='margin:0;'>" & MainParagraph & "</p><p style='margin:8px 0 0 0;'>" & SecondaryParagraph & "</p></div>"
		displayFolder: Insights\COVID Impact
		lineageTag: e6cee53e-6503-4cfb-9214-3e779f156c8b

	measure 'Funnel Floor Bias Tooltip' = ```

			VAR OverallRate = FORMAT([Overall Conversion Rate], "0.0%")
			VAR MainParagraph = "Every conversion rate in this report - including the overall " & OverallRate & " - is measured from first product view onward. This dataset has no event for a raw site visit, search, or homepage browse that never touched a product page."
			VAR SecondaryParagraph = "About 214,000 sessions have a cart or purchase event but zero logged views - proof there's real traffic above 'viewed a product' this data simply can't see. True top-of-funnel conversion is almost certainly lower than " & OverallRate & ", but isn't computable from this data."
			RETURN
			    "<div style='font-family:""Segoe UI Light"",""Segoe UI"",sans-serif;font-weight:300;color:#FFFFFF;font-size:13px;text-align:justify;'><p style='margin:0;'>" & MainParagraph & "</p><p style='margin:8px 0 0 0;'>" & SecondaryParagraph & "</p></div>"

			```
		lineageTag: c2b93446-1913-4d37-a72d-40501e5584f0

	/// Explainability tooltip for the Total Events KPI card - definition pulled live from the Data Dictionary, paired with a per-purchasing-user ratio for scale. Bind to an HTML Content visual on the 'overview-total-events-tooltip' page.
	measure 'Total Events Tooltip' =
			VAR Def = LOOKUPVALUE(DataDictionary_Measures[Description], DataDictionary_Measures[Name], "Total Events")
			VAR EventsPerBuyer = FORMAT(DIVIDE([Total Events], [Purchasing Users]), "0")
			RETURN
			    "<div style='font-family:""Segoe UI Light"",""Segoe UI"",sans-serif;font-weight:300;color:#FFFFFF;font-size:13px;text-align:justify;'>" &
			        "<p style='margin:0;'>" & Def & "</p>" &
			        "<p style='margin:8px 0 0 0;'>That works out to roughly " & EventsPerBuyer & " tracked events for every user who went on to purchase.</p>" &
			    "</div>"
		displayFolder: Tooltips\Overview
		lineageTag: 31a57712-ade3-4b0f-9726-3cd631c6df72

	/// Explainability tooltip for the Purchasing Users KPI card - definition pulled live from the Data Dictionary, paired with the conversion rate these users represent. Bind to an HTML Content visual on the 'overview-purchasing-users-tooltip' page.
	measure 'Purchasing Users Tooltip' =
			VAR Def = LOOKUPVALUE(DataDictionary_Measures[Description], DataDictionary_Measures[Name], "Purchasing Users")
			VAR RevPerBuyer = FORMAT(DIVIDE([Total Revenue], [Purchasing Users]), "$#,##0")
			RETURN
			    "<div style='font-family:""Segoe UI Light"",""Segoe UI"",sans-serif;font-weight:300;color:#FFFFFF;font-size:13px;text-align:justify;'>" &
			        "<p style='margin:0;'>" & Def & "</p>" &
			        "<p style='margin:8px 0 0 0;'>On average, each of these customers generated about " & RevPerBuyer & " in revenue over the tracked period.</p>" &
			    "</div>"
		displayFolder: Tooltips\Overview
		lineageTag: 5256b61a-d64a-4b67-86cb-c15e12fcc1ad

	column Value
		isHidden
		lineageTag: a861b4e5-d496-4bae-9bed-e7872af11c91
		isNameInferred
		sourceColumn: [Value]

	partition _Measures = calculated
		mode: import
		source = {1}

	annotation PBI_Id = 6a3f8e2d4c1b4f9a8e7d2c5b1a0f3e6d

