table _Measures
	lineageTag: 8f2b6e5a-1c4d-4a3e-9f7b-2d6e8a0c5b1f

	/// Total number of tracked events (views, cart adds, purchases) across the entire dataset, October 2019 through April 2020. Fixed value from the verified BigQuery row count - this model doesn't import raw event-level data, so it can't be recalculated from what's here.
	measure 'Total Events' = 411709736
		formatString: #,##0
		displayFolder: 'Overview KPIs'
		lineageTag: f40b8719-ee36-452f-99c1-5a7113673ff8

	/// Number of distinct users who made at least one purchase during the tracked period. Fixed value from the RFM analysis - user-level detail isn't imported into this model.
	measure 'Purchasing Users' = 2064899
		formatString: #,##0
		displayFolder: 'Overview KPIs'
		lineageTag: d6a46e5e-244e-4231-8482-fd7b3c35ad64

	/// Share of all product views across the entire dataset that led to a purchase, covering all 14 categories. Fixed value - the FactFunnelByCategory table only holds the top 10 categories, so recalculating from it here would undercount.
	measure 'Overall Conversion Rate' = 0.0609
		formatString: 0.0%
		displayFolder: 'Overview KPIs'
		lineageTag: 85658db1-2ce6-48eb-8965-e2649a28847b

		annotation PBI_FormatHint = {"isCustom":true}

	/// Total purchase revenue across all 14 categories, in US dollars. Fixed value for the same reason as Overall Conversion Rate - the imported category tables only cover a subset.
	measure 'Total Revenue' = 2060000000
		formatString: "$"#,##0
		displayFolder: 'Overview KPIs'
		lineageTag: 14a1b683-6977-4e98-87e6-c7c9010d0595

	/// Share of shopping-cart sessions that never turned into a purchase. Fixed value, calculated from the full dataset outside this model.
	measure 'Cart Abandonment Rate' = 0.5409
		formatString: 0.0%
		displayFolder: 'Overview KPIs'
		lineageTag: 75a7afe1-ecc7-4e7d-9e34-e1668d620cd1

		annotation PBI_FormatHint = {"isCustom":true}

	/// Share of total revenue that comes from the 'Champion' customer segment (the top tier in the Recency-Frequency-Monetary scoring model). Recalculates live from FactRFMSegment, since that table covers all 6 segments.
	measure 'Champion Revenue Share' = CALCULATE(SUM(FactRFMSegment[PctRevenue]), FactRFMSegment[Segment] = "Champion")
		formatString: 0.0%
		displayFolder: 'Overview KPIs'
		lineageTag: 5a198fd3-390d-4041-bd75-d128789c330c

		annotation PBI_FormatHint = {"isCustom":true}

	/// Average share of customers still active one month after their first purchase, averaged across all acquisition cohorts. Recalculates live from FactRetentionCurve.
	measure 'Month-1 Retention Avg' = CALCULATE(SUM(FactRetentionCurve[AvgRetention]), FactRetentionCurve[MonthsSinceFirst] = "M1")
		formatString: 0.00%
		displayFolder: 'Overview KPIs'
		lineageTag: d70921b5-9452-40d9-83ad-443a9e525873

	/// How much session-level conversion rate changed comparing the period before COVID-19 lockdowns to the period right after they began. A positive number means conversion went up. Recalculates live from FactCovidComparison.
	measure 'COVID Session Conversion Lift' = VAR PreValue = CALCULATE(SUM(FactCovidComparison[PreCovid]), FactCovidComparison[Metric] = "Session Conversion %") VAR OnsetValue = CALCULATE(SUM(FactCovidComparison[CovidOnset]), FactCovidComparison[Metric] = "Session Conversion %") RETURN DIVIDE(OnsetValue - PreValue, PreValue)
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: 'Overview KPIs'
		lineageTag: 7aad4945-6362-4370-9e07-6ba017a7676e

	/// Hex color code (green or red) reflecting whether the COVID Session Conversion Lift measure is positive or negative. Feeds the badge background on the 'COVID Lift KPI Card' HTML Content visual - not meant to be used directly in a chart.
	measure 'COVID Lift Color' = IF ( [COVID Session Conversion Lift] >= 0, "#2ECC71", "#E74C3C" )
		displayFolder: HTML Cards
		lineageTag: 3c30c61a-a086-4895-98e9-a4232732d3b4

	/// Plain-language read of whether conversion improved or declined after COVID-19 onset, driven by the sign of COVID Session Conversion Lift. Feeds the 'COVID Lift KPI Card' HTML Content visual - not meant to be used directly in a chart.
	measure 'COVID Lift Direction Text' =
			IF (
			    [COVID Session Conversion Lift] >= 0,
			    "Conversion rate improved after COVID-19 onset",
			    "Conversion rate declined after COVID-19 onset"
			)
		displayFolder: HTML Cards
		lineageTag: fd3ca5f4-1b97-4b54-99f5-d13da1bdc822

	/// Self-contained HTML/CSS string combining the COVID Session Conversion Lift value, a color-coded badge, and a plain-language interpretation - built for the HTML Content custom visual, which renders whatever HTML a bound measure returns. Demonstrates a compound KPI card a native Power BI card visual can't produce in a single tile. Bind this measure to the visual's data role.
	measure 'COVID Lift KPI Card' =
			VAR LiftValue = FORMAT ( [COVID Session Conversion Lift], "+0.0%;-0.0%;0.0%" )
			VAR BadgeColor = [COVID Lift Color]
			VAR DirectionText = [COVID Lift Direction Text]
			RETURN
			    "<div style='font-family:Segoe UI,sans-serif;text-align:center;padding:12px;'>" &
			        "<div style='font-size:12px;color:#9B9BA8;text-transform:uppercase;letter-spacing:0.5px;'>COVID Impact on Conversion</div>" &
			        "<div style='font-size:32px;font-weight:700;color:#FFFFFF;margin-top:4px;'>" & LiftValue & "</div>" &
			        "<div style='display:inline-block;margin-top:8px;padding:4px 12px;border-radius:12px;font-size:12px;font-weight:600;color:white;background-color:" & BadgeColor & ";'>" & DirectionText & "</div>" &
			    "</div>"
		displayFolder: HTML Cards
		lineageTag: e56ed8dc-76de-4659-9d04-7156ddab4b5d

	/// Where the current Month-1 Retention Avg sits between the lowest and highest single-cohort M1 retention on record (0 = at the historical low, 1 = at the historical high). Feeds the badge on the 'Month-1 Retention KPI Card' - not meant to be used directly in a chart.
	measure 'Retention Position Ratio' =
			VAR M1Avg = [Month-1 Retention Avg]
			VAR M1Min = CALCULATE(SUM(FactRetentionCurve[MinRetention]), FactRetentionCurve[MonthsSinceFirst] = "M1")
			VAR M1Max = CALCULATE(SUM(FactRetentionCurve[MaxRetention]), FactRetentionCurve[MonthsSinceFirst] = "M1")
			RETURN DIVIDE(M1Avg - M1Min, M1Max - M1Min)
		displayFolder: HTML Cards
		lineageTag: deca8e6b-02b5-4b6d-a417-735ac0af1347

	/// Plain-language read of where the current Month-1 Retention Avg sits relative to the historical range of individual cohorts, based on Retention Position Ratio. Feeds the 'Month-1 Retention KPI Card' - not meant to be used directly in a chart.
	measure 'Retention Position Text' =
			VAR Ratio = [Retention Position Ratio]
			RETURN
			    SWITCH(
			        TRUE(),
			        Ratio < 0.33, "Toward the lower end of the historical cohort range",
			        Ratio > 0.67, "Toward the higher end of the historical cohort range",
			        "In the middle of the historical cohort range"
			    )
		displayFolder: HTML Cards
		lineageTag: adc6ce70-bef6-4b0b-a4c5-fcb55e0338b1

	/// Hex color code (amber/blue/green) reflecting whether the current Month-1 Retention Avg sits in the lower, middle, or upper third of the historical cohort range. Feeds the badge background on the 'Month-1 Retention KPI Card' - not meant to be used directly in a chart.
	measure 'Retention Position Color' =
			VAR Ratio = [Retention Position Ratio]
			RETURN
			    SWITCH(
			        TRUE(),
			        Ratio < 0.33, "#E67E22",
			        Ratio > 0.67, "#2ECC71",
			        "#5B8DBE"
			    )
		displayFolder: HTML Cards
		lineageTag: 4151cde0-9079-4246-baa9-659ce86836d3

	/// Self-contained HTML/CSS string combining the Month-1 Retention Avg value with a badge showing where it sits relative to the historical range of individual cohorts (min-max from FactRetentionCurve) - not an external benchmark, purely this dataset's own cohort history. Bind this measure to an HTML Content visual's data role.
	measure 'Month-1 Retention KPI Card' =
			VAR RetentionValue = FORMAT ( [Month-1 Retention Avg], "0.0%" )
			VAR BadgeColor = [Retention Position Color]
			VAR PositionText = [Retention Position Text]
			RETURN
			    "<div style='font-family:Segoe UI,sans-serif;text-align:center;padding:12px;'>" &
			        "<div style='font-size:12px;color:#9B9BA8;text-transform:uppercase;letter-spacing:0.5px;'>Month-1 Retention Avg</div>" &
			        "<div style='font-size:32px;font-weight:700;color:#FFFFFF;margin-top:4px;'>" & RetentionValue & "</div>" &
			        "<div style='display:inline-block;margin-top:8px;padding:4px 12px;border-radius:12px;font-size:12px;font-weight:600;color:white;background-color:" & BadgeColor & ";'>" & PositionText & "</div>" &
			    "</div>"
		displayFolder: HTML Cards
		lineageTag: e9cf188e-6674-4aee-9dc7-6ea8e5c46f75

	/// Single dynamic sentence synthesizing the Overview page's core story - conversion rate, cart abandonment, and month-1 retention - recalculated live from the model so it never goes stale if someone filters the page differently. Not a static caption; reuses the Retention Position Ratio logic already built for the retention KPI card. Bind directly to a text-based visual (Card, HTML Content, or a text box referencing this measure).
	measure 'Overview Insight' =
			VAR ConvRate = FORMAT ( [Overall Conversion Rate], "0.0%" )
			VAR AbandonRate = FORMAT ( [Cart Abandonment Rate], "0.0%" )
			VAR RetentionRate = FORMAT ( [Month-1 Retention Avg], "0.0%" )
			VAR Ratio = [Retention Position Ratio]
			VAR RetentionFraming =
			    SWITCH(
			        TRUE(),
			        Ratio < 0.33, "toward the weaker end of the historical range",
			        Ratio > 0.67, "toward the stronger end of the historical range",
			        "roughly mid-range historically"
			    )
			VAR InsightText = ConvRate & " of views convert and " & AbandonRate & " of carts are abandoned; first-month retention lands at " & RetentionRate & ", " & RetentionFraming & "."
			RETURN
			    "<div style='font-family:Segoe UI,sans-serif;color:#FFFFFF;font-size:20px;'>" & InsightText & "</div>"
		displayFolder: Insights\Overview
		lineageTag: 709af52b-ac37-4ed3-807f-9eb8ac924e30

	/// Single dynamic sentence comparing how strongly session depth, category, and brand each swing conversion rate - recalculates live so the multiples always match current data. Also dynamically checks whichever category currently ranks #1 by conversion against the TaxonomyMislabeledFlag column, only appending the taxonomy caveat if the actual top-ranked category is the flagged one (does not hardcode a category name). Bind to an HTML Content visual's data role.
	measure 'Funnel Insight' =
			VAR TopCategoryTable =
			    TOPN(1, SUMMARIZE(FactFunnelByCategory, FactFunnelByCategory[CategoryCode], "CatRate", [Category Conversion Rate]), [CatRate], DESC)
			VAR TopCategoryCode = MAXX(TopCategoryTable, FactFunnelByCategory[CategoryCode])
			VAR TopCategoryDisplayName = LOOKUPVALUE(DimCategory[DisplayName], DimCategory[CategoryCode], TopCategoryCode)
			VAR TopCategoryFlagged = LOOKUPVALUE(DimCategory[TaxonomyMislabeledFlag], DimCategory[CategoryCode], TopCategoryCode)
			VAR SessionMin = MINX(VALUES(FactSessionDepth[EventBucket]), [Session Conversion Rate])
			VAR SessionMax = MAXX(VALUES(FactSessionDepth[EventBucket]), [Session Conversion Rate])
			VAR SessionSwing = FORMAT(DIVIDE(SessionMax, SessionMin), "0")
			VAR MainParagraph =
			    "How much someone browses matters far more than what they browse. Visitors who view just one product almost never buy, but conversion climbs sharply the more they look around, leveling off once someone's clearly engaged - a swing of roughly " & SessionSwing & "x between the least and most engaged visitors, dwarfing anything category or brand choice can explain."
			VAR CaveatParagraph =
			    IF(
			        TopCategoryFlagged = "Y",
			        "<p style='margin:8px 0 0 0;'>Note: the top category shown, " & TopCategoryDisplayName & ", has a known data quality flag - see Data Quality Findings for details. More detail is available on the Category & Brand page.</p>",
			        ""
			    )
			RETURN
			    "<div style='font-family:Segoe UI,sans-serif;color:#FFFFFF;font-size:15px;text-align:justify;'><p style='margin:0;'>" & MainParagraph & "</p>" & CaveatParagraph & "</div>"
		displayFolder: Insights\Funnel
		lineageTag: 7e44e649-7356-471c-8c8f-cc7ad0f3ca6a

	/// Single dynamic paragraph summarizing revenue concentration across categories and brands - which category and which brand actually dominate revenue on this page, expressed as a share of total. Dynamically checks whichever category currently ranks #1 by revenue against the TaxonomyMislabeledFlag column, only appending the caveat if the actual top-ranked category is the flagged one. Bind to an HTML Content visual's data role.
	measure 'Category Brand Insight' =
			VAR TopCategoryTable =
			    TOPN(1, SUMMARIZE(FactCategoryPerformance, FactCategoryPerformance[CategoryCode], "Rev", CALCULATE(SUM(FactCategoryPerformance[TotalRevenue]))), [Rev], DESC)
			VAR TopCategoryCode = MAXX(TopCategoryTable, FactCategoryPerformance[CategoryCode])
			VAR TopCategoryRevenue = MAXX(TopCategoryTable, [Rev])
			VAR TopCategoryDisplayName = LOOKUPVALUE(DimCategory[DisplayName], DimCategory[CategoryCode], TopCategoryCode)
			VAR TopCategoryFlagged = LOOKUPVALUE(DimCategory[TaxonomyMislabeledFlag], DimCategory[CategoryCode], TopCategoryCode)
			VAR TotalCategoryRevenue = SUM(FactCategoryPerformance[TotalRevenue])
			VAR CategoryShare = FORMAT(DIVIDE(TopCategoryRevenue, TotalCategoryRevenue), "0%")
			VAR TopBrandTable =
			    TOPN(1, SUMMARIZE(FactTopBrands, FactTopBrands[Brand], "Rev", CALCULATE(SUM(FactTopBrands[TotalRevenue]))), [Rev], DESC)
			VAR TopBrandName = MAXX(TopBrandTable, FactTopBrands[Brand])
			VAR TopBrandRevenue = MAXX(TopBrandTable, [Rev])
			VAR TotalBrandRevenue = SUM(FactTopBrands[TotalRevenue])
			VAR BrandShare = FORMAT(DIVIDE(TopBrandRevenue, TotalBrandRevenue), "0%")
			VAR TopBrandDisplayName = UPPER(LEFT(TopBrandName, 1)) & MID(TopBrandName, 2, LEN(TopBrandName))
			VAR MainParagraph =
			    IF(
			        TopCategoryFlagged = "Y",
			        "<p style='margin:0;font-weight:600;color:#E67E22;'>On the surface, " & TopCategoryDisplayName & " looks like it drives " & CategoryShare & " of all category revenue here - but that is an illusion: since December 2019, Apple/Samsung/Xiaomi products were reclassified into this category from Electronics, so it is really consumer electronics revenue hiding under the wrong label.</p>" &
			        "<p style='margin:8px 0 0 0;'>Strip that out, and the real concentration story is on the brand side: " & TopBrandDisplayName & " alone accounts for " & BrandShare & " of brand revenue shown here - more than every other brand combined.</p>",
			        "<p style='margin:0;'>" & TopCategoryDisplayName & " alone accounts for " & CategoryShare & " of the category revenue shown here, and " & TopBrandDisplayName & " a similar " & BrandShare & " of brand revenue - a handful of players carry most of the weight on this page, not a broad spread across categories or brands.</p>"
			    )
			RETURN
			    "<div style='font-family:Segoe UI,sans-serif;color:#FFFFFF;font-size:13px;text-align:justify;'>" & MainParagraph & "</div>"
		displayFolder: Insights\Category & Brand
		lineageTag: a64934ed-8a48-4e36-9a0a-960172c018ae

	column Value
		lineageTag: a861b4e5-d496-4bae-9bed-e7872af11c91
		isNameInferred
		sourceColumn: [Value]

	partition _Measures = calculated
		mode: import
		source = {1}

	annotation PBI_Id = 6a3f8e2d4c1b4f9a8e7d2c5b1a0f3e6d

