table DimMonthsSinceFirst
	lineageTag: b8b5d3cd-0e23-4bf4-ae85-56678844dcf1

	column MonthsSinceFirst
		dataType: string
		lineageTag: 7edf2278-078d-44d0-bf79-6dae052da8c4
		summarizeBy: none
		sourceColumn: MonthsSinceFirst

		annotation SummarizationSetBy = Automatic

	column SortOrder
		dataType: int64
		formatString: 0
		lineageTag: 93b02d3a-9722-485c-9525-66dc08d2fb92
		summarizeBy: none
		sourceColumn: SortOrder

		annotation SummarizationSetBy = Automatic

	partition DimMonthsSinceFirst = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Jean-Yves TRAN\FOR_GITHUB\Data_Analyst_Projects\project2_ecommerce_behavior_analytics\dashboards\powerbi_source_data.xlsx"), null, true),
				    DimMonthsSinceFirst_Sheet = Source{[Item="DimMonthsSinceFirst",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(DimMonthsSinceFirst_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"MonthsSinceFirst", type text}, {"SortOrder", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

