table FactCohortRetention
	lineageTag: 52a82955-2fcf-413f-a88b-47791befc0aa

	/// Average retention rate across all acquisition cohorts and all months after first purchase, excluding the trivial 'month zero' point (where retention is always 100% by definition, since everyone is active in their own signup month). Weighted by each cohort's actual size, so large cohorts count more than small ones.
	measure 'Weighted Avg Retention' = VAR NonZeroMonths = FILTER(FactCohortRetention, FactCohortRetention[MonthsSinceFirst] <> "M0") RETURN DIVIDE(SUMX(NonZeroMonths, FactCohortRetention[RetentionRate] * RELATED(DimCohortMonth[CohortUsers])), SUMX(NonZeroMonths, RELATED(DimCohortMonth[CohortUsers])))
		formatString: 0.00%
		displayFolder: 'Customer Segments'
		lineageTag: e6b68ad1-8aaf-4a35-927d-3cbff41f5c65

	/// Links to DimCohortMonth - the month this cohort of customers first purchased.
	column CohortMonth
		dataType: dateTime
		formatString: Long Date
		lineageTag: c9fba6c7-c303-4563-9f09-497013afdb98
		summarizeBy: none
		sourceColumn: CohortMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Links to DimMonthsSinceFirst - how many months after first purchase this retention figure applies to.
	column MonthsSinceFirst
		dataType: string
		lineageTag: 10274f1d-5470-48b8-819a-e421be89e40d
		summarizeBy: none
		sourceColumn: MonthsSinceFirst

		annotation SummarizationSetBy = Automatic

	/// Share of this cohort still active (made a purchase) this many months after their first purchase. Combinations the dataset can't yet observe (e.g. a cohort's retention 6 months out, if the dataset doesn't extend that far) are intentionally left out of this table rather than shown as 0% - a blank means 'not yet observable,' not 'nobody came back.'
	column RetentionRate
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6b44cd2c-77df-4af0-822b-0b0680e6ed88
		summarizeBy: none
		sourceColumn: RetentionRate

		annotation SummarizationSetBy = Automatic

	partition FactCohortRetention = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Jean-Yves TRAN\FOR_GITHUB\Data_Analyst_Projects\project2_ecommerce_behavior_analytics\dashboards\powerbi_source_data.xlsx"), null, true),
				    FactCohortRetention_Sheet = Source{[Item="FactCohortRetention",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(FactCohortRetention_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CohortMonth", type date}, {"MonthsSinceFirst", type text}, {"RetentionRate", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

