table FactConvertingVsNon
	lineageTag: 5d52df32-3950-4096-80f6-896282b77b9d

	/// Median session duration formatted as minutes and seconds (e.g. '4m 23s') instead of raw decimal minutes, which read ambiguously in the Converting vs. Non-Converting table (4.38 looks like it could mean 4 minutes 38 seconds rather than its actual value of 4 minutes 23 seconds). Use this measure in place of the raw MedianDurationMin column in any visual.
	measure 'Median Session Duration (mm:ss)' =
			VAR TotalMinutes = AVERAGE(FactConvertingVsNon[MedianDurationMin])
			VAR TotalSeconds = ROUND(TotalMinutes * 60, 0)
			VAR WholeMinutes = INT(TotalSeconds / 60)
			VAR RemainingSeconds = MOD(TotalSeconds, 60)
			RETURN WholeMinutes & "m " & FORMAT(RemainingSeconds, "00") & "s"
		displayFolder: Customer Segments
		lineageTag: 547af219-3803-49f7-8818-94917b6bb89a

	/// Combined session count across both Converting and Non-Converting, ignoring the row-level SessionType filter so every row sees the same grand total. Built to bind as the Maximum value on the Total Sessions column's Data bar conditional formatting, so each row's bar length represents its true share of all sessions rather than an arbitrary per-row scale.
	measure 'Total Sessions Grand Total' = CALCULATE(SUM(FactConvertingVsNon[Sessions]), ALL(FactConvertingVsNon[SessionType]))
		formatString: #,##0
		displayFolder: Customer Segments
		lineageTag: 903d57cd-951e-4488-87b7-7d8569bc4ea7

	/// Either 'Converting' (session included a purchase) or 'Non-Converting'.
	column SessionType
		dataType: string
		lineageTag: dd973f2f-6d12-4348-b467-51444e00135d
		summarizeBy: none
		sourceColumn: SessionType

		annotation SummarizationSetBy = Automatic

	/// Number of sessions of this type.
	column Sessions
		dataType: int64
		formatString: 0
		lineageTag: 187353da-6802-42a7-ae92-0f2abbc5c3f4
		summarizeBy: sum
		sourceColumn: Sessions

		annotation SummarizationSetBy = Automatic

	/// Average number of events per session, for this session type only. Don't sum or average across the two session types.
	column AvgEvents
		dataType: double
		lineageTag: db0d7f3f-b33b-4f58-a5a2-761f0256e075
		summarizeBy: none
		sourceColumn: AvgEvents

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Median number of events per session, for this session type only.
	column MedianEvents
		dataType: int64
		formatString: 0
		lineageTag: bd53c9e5-0ea7-477d-9ba0-4d02fa96ecd2
		summarizeBy: none
		sourceColumn: MedianEvents

		annotation SummarizationSetBy = Automatic

	/// Average number of cart-add events per session, for this session type only.
	column AvgCarts
		dataType: double
		lineageTag: d330f2d1-7a51-46a8-8a22-949d4342c88d
		summarizeBy: none
		sourceColumn: AvgCarts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Median session length in minutes, for this session type only.
	column MedianDurationMin
		dataType: double
		lineageTag: 54bde311-16f4-4d1d-b42a-d129a5daafb1
		summarizeBy: none
		sourceColumn: MedianDurationMin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactConvertingVsNon = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Jean-Yves TRAN\FOR_GITHUB\Data_Analyst_Projects\project2_ecommerce_behavior_analytics\dashboards\powerbi_source_data.xlsx"), null, true),
				    FactConvertingVsNon_Sheet = Source{[Item="FactConvertingVsNon",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(FactConvertingVsNon_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SessionType", type text}, {"Sessions", Int64.Type}, {"AvgEvents", type number}, {"MedianEvents", Int64.Type}, {"AvgCarts", type number}, {"MedianDurationMin", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

