table FactFunnelByCategory
	lineageTag: 3a1b3cf8-4f1a-43f6-b941-013e118019a1

	/// View-to-purchase conversion rate across whichever categories are currently selected, calculated as total purchases divided by total views - not an average of each category's individual rate. This gives the correct blended rate when more than one category is selected; averaging the percentages directly would unfairly weight small categories the same as large ones.
	measure 'Category Conversion Rate' = DIVIDE(SUM(FactFunnelByCategory[Purchases]), SUM(FactFunnelByCategory[Views]))
		formatString: 0.00%
		displayFolder: Funnel
		lineageTag: 4b425cbc-ceb2-4cf9-9949-874a190cf9dc

	/// Links to DimCategory. One row per one of the top 10 categories by conversion rate - not all 14 (see the README's Module 1 section for the full category list).
	column CategoryCode
		dataType: string
		lineageTag: 5b01728c-9e39-42a7-9b42-061ec192ebc3
		summarizeBy: none
		sourceColumn: CategoryCode

		annotation SummarizationSetBy = Automatic

	/// Total product-view events for this category.
	column Views
		dataType: int64
		formatString: 0
		lineageTag: 3398badd-d4d0-4cfc-a76c-d24e70259b79
		summarizeBy: sum
		sourceColumn: Views

		annotation SummarizationSetBy = Automatic

	/// Total add-to-cart events for this category.
	column Carts
		dataType: int64
		formatString: 0
		lineageTag: 82059fbf-12b8-4bc6-96e7-24945be77291
		summarizeBy: sum
		sourceColumn: Carts

		annotation SummarizationSetBy = Automatic

	/// Total purchase events for this category.
	column Purchases
		dataType: int64
		formatString: 0
		lineageTag: f7377d7b-b71c-4ef5-bf1e-e2f56a7572c2
		summarizeBy: sum
		sourceColumn: Purchases

		annotation SummarizationSetBy = Automatic

	/// This specific category's view-to-purchase conversion rate. Read per-row only - don't sum or average this column across categories; use the 'Category Conversion Rate' measure instead for a correctly blended figure.
	column ConversionPct
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b9a644bf-8115-4a2c-b13a-38843268123e
		summarizeBy: none
		sourceColumn: ConversionPct

		annotation SummarizationSetBy = Automatic

	partition FactFunnelByCategory = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Jean-Yves TRAN\FOR_GITHUB\Data_Analyst_Projects\project2_ecommerce_behavior_analytics\dashboards\powerbi_source_data.xlsx"), null, true),
				    FactFunnelByCategory_Sheet = Source{[Item="FactFunnelByCategory",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(FactFunnelByCategory_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CategoryCode", type text}, {"Views", Int64.Type}, {"Carts", Int64.Type}, {"Purchases", Int64.Type}, {"ConversionPct", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

