table FactCategoryPerformance
	lineageTag: a9a65881-26b7-4fcd-8a00-2a528be9aa42

	/// Average purchase price across whichever categories are selected, calculated as total revenue divided by total purchases. Gives a correctly blended price across multiple categories, unlike averaging each category's individual average price.
	measure 'Weighted Avg Price' = DIVIDE(SUM(FactCategoryPerformance[TotalRevenue]), SUM(FactCategoryPerformance[Purchases]))
		formatString: "$"#,##0.00
		displayFolder: 'Category & Brand'
		lineageTag: 306249a2-b7ed-4e38-b8c0-2e5827a49a7e

	/// Links to DimCategory. One row per one of the top 8 categories by revenue.
	column CategoryCode
		dataType: string
		lineageTag: 67172dbf-ab81-47ba-b290-ee4b296842e3
		summarizeBy: none
		sourceColumn: CategoryCode

		annotation SummarizationSetBy = Automatic

	/// Total product-view events for this category.
	column Views
		dataType: int64
		formatString: 0
		lineageTag: 6d338203-da33-4dfb-ad4b-d86d8fd15825
		summarizeBy: sum
		sourceColumn: Views

		annotation SummarizationSetBy = Automatic

	/// Total purchase events for this category.
	column Purchases
		dataType: int64
		formatString: 0
		lineageTag: 37788b1c-9cab-432f-a406-cc0e4e3a842f
		summarizeBy: sum
		sourceColumn: Purchases

		annotation SummarizationSetBy = Automatic

	/// Total revenue from this category, in US dollars.
	column TotalRevenue
		dataType: int64
		formatString: 0
		lineageTag: b95406cd-d9de-4202-9a10-bb0d501d7fd5
		summarizeBy: sum
		sourceColumn: TotalRevenue

		annotation SummarizationSetBy = Automatic

	/// Average purchase price for this category. Read per-row only - use the 'Weighted Avg Price' measure for a correctly blended figure across multiple categories.
	column AvgPrice
		dataType: double
		lineageTag: 646ac75b-fc6f-428c-8ef3-0ed3d1f41b02
		summarizeBy: none
		sourceColumn: AvgPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactCategoryPerformance = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Jean-Yves TRAN\FOR_GITHUB\Data_Analyst_Projects\project2_ecommerce_behavior_analytics\dashboards\powerbi_source_data.xlsx"), null, true),
				    FactCategoryPerformance_Sheet = Source{[Item="FactCategoryPerformance",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(FactCategoryPerformance_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CategoryCode", type text}, {"Views", Int64.Type}, {"Purchases", Int64.Type}, {"TotalRevenue", Int64.Type}, {"AvgPrice", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

