table FactTopBrands
	lineageTag: 14ab2cbb-4a2b-4784-a4cd-b7f0133dc6f5

	/// Average purchase price across whichever brands are selected, calculated as total revenue divided by total purchases. Gives a correctly blended price across multiple brands.
	measure 'Brand Weighted Avg Price' = DIVIDE(SUM(FactTopBrands[TotalRevenue]), SUM(FactTopBrands[Purchases]))
		formatString: "$"#,##0.00
		displayFolder: 'Category & Brand'
		lineageTag: ec7ed343-e675-4ec3-ac69-7bb5b1a4aa56

	/// Links to DimBrand. Covers all 10 brands tracked in the top-brands analysis.
	column Brand
		dataType: string
		lineageTag: a69b34fd-e236-4118-9399-1aea377afbac
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	/// Total purchase events for this brand.
	column Purchases
		dataType: int64
		formatString: 0
		lineageTag: 478fd042-ae5d-4377-b9e0-175e1f06cadf
		summarizeBy: sum
		sourceColumn: Purchases

		annotation SummarizationSetBy = Automatic

	/// Total revenue from this brand, in US dollars.
	column TotalRevenue
		dataType: int64
		formatString: 0
		lineageTag: d1f77856-a6af-45ff-9e1b-30747ac3108f
		summarizeBy: sum
		sourceColumn: TotalRevenue

		annotation SummarizationSetBy = Automatic

	/// Average purchase price for this brand. Read per-row only - use the 'Brand Weighted Avg Price' measure for a correctly blended figure across multiple brands.
	column AvgPrice
		dataType: double
		lineageTag: 1f308250-a735-4982-bf7e-cc18d19d0048
		summarizeBy: none
		sourceColumn: AvgPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of distinct product categories this brand sells in.
	column CategoriesCount
		dataType: int64
		formatString: 0
		lineageTag: 24ff4a7c-4dd8-49a4-a7a2-9828e8ffbec8
		summarizeBy: none
		sourceColumn: CategoriesCount

		annotation SummarizationSetBy = Automatic

	partition FactTopBrands = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Jean-Yves TRAN\FOR_GITHUB\Data_Analyst_Projects\project2_ecommerce_behavior_analytics\dashboards\powerbi_source_data.xlsx"), null, true),
				    FactTopBrands_Sheet = Source{[Item="FactTopBrands",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(FactTopBrands_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Brand", type text}, {"Purchases", Int64.Type}, {"TotalRevenue", Int64.Type}, {"AvgPrice", type number}, {"CategoriesCount", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

