table FactFunnelByCategory
	lineageTag: 3a1b3cf8-4f1a-43f6-b941-013e118019a1

	column CategoryCode
		dataType: string
		lineageTag: 5b01728c-9e39-42a7-9b42-061ec192ebc3
		summarizeBy: none
		sourceColumn: CategoryCode

		annotation SummarizationSetBy = Automatic

	column Views
		dataType: int64
		formatString: 0
		lineageTag: 3398badd-d4d0-4cfc-a76c-d24e70259b79
		summarizeBy: sum
		sourceColumn: Views

		annotation SummarizationSetBy = Automatic

	column Carts
		dataType: int64
		formatString: 0
		lineageTag: 82059fbf-12b8-4bc6-96e7-24945be77291
		summarizeBy: sum
		sourceColumn: Carts

		annotation SummarizationSetBy = Automatic

	column Purchases
		dataType: int64
		formatString: 0
		lineageTag: f7377d7b-b71c-4ef5-bf1e-e2f56a7572c2
		summarizeBy: sum
		sourceColumn: Purchases

		annotation SummarizationSetBy = Automatic

	column ConversionPct
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b9a644bf-8115-4a2c-b13a-38843268123e
		summarizeBy: none
		sourceColumn: ConversionPct

		annotation SummarizationSetBy = Automatic

	measure 'Category Conversion Rate' = DIVIDE(SUM(FactFunnelByCategory[Purchases]), SUM(FactFunnelByCategory[Views]))
		formatString: 0.00%
		displayFolder: Funnel

	partition FactFunnelByCategory = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Jean-Yves TRAN\FOR_GITHUB\Data_Analyst_Projects\project2_ecommerce_behavior_analytics\dashboards\powerbi_source_data.xlsx"), null, true),
				    FactFunnelByCategory_Sheet = Source{[Item="FactFunnelByCategory",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(FactFunnelByCategory_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CategoryCode", type text}, {"Views", Int64.Type}, {"Carts", Int64.Type}, {"Purchases", Int64.Type}, {"ConversionPct", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

