table FactCategoryMixShift
	lineageTag: 1e558c4d-1180-4c4c-b2f6-51a012a48b6b

	/// Links to DimCategory. Covers only the 6 categories whose revenue share moved the most around COVID onset - not all 14.
	column CategoryCode
		dataType: string
		lineageTag: 638babfe-2c1c-4c49-ac83-537f13e99f4c
		summarizeBy: none
		sourceColumn: CategoryCode

		annotation SummarizationSetBy = Automatic

	/// This category's share of total revenue before COVID onset. Because this table only lists 6 of 14 categories, don't sum this column expecting it to reach 100%.
	column PreCovidSharePct
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0ca9576b-673c-4621-9d88-a2997ad39aba
		summarizeBy: none
		sourceColumn: PreCovidSharePct

		annotation SummarizationSetBy = Automatic

	/// This category's share of total revenue after COVID onset, for comparison against PreCovidSharePct.
	column CovidSharePct
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: fd677329-7901-4b28-ae93-d95a877ea21e
		summarizeBy: none
		sourceColumn: CovidSharePct

		annotation SummarizationSetBy = Automatic

	/// Change in revenue share for this category, in percentage points (COVID-onset share minus pre-COVID share). Positive means this category grew its share of the pie during COVID.
	column DeltaPP
		dataType: double
		lineageTag: 1290d4d2-e96c-407a-95c1-0e0c6a3e0d40
		summarizeBy: none
		sourceColumn: DeltaPP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactCategoryMixShift = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Jean-Yves TRAN\FOR_GITHUB\Data_Analyst_Projects\project2_ecommerce_behavior_analytics\dashboards\powerbi_source_data.xlsx"), null, true),
				    FactCategoryMixShift_Sheet = Source{[Item="FactCategoryMixShift",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(FactCategoryMixShift_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CategoryCode", type text}, {"PreCovidSharePct", type number}, {"CovidSharePct", type number}, {"DeltaPP", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

