table FactSessionDepth
	lineageTag: e062110c-7784-4896-9a01-d5c2bb19ba3b

	/// Conversion rate across whichever session-depth buckets are selected, calculated as total purchasing sessions divided by total sessions. Gives a correctly blended rate, unlike averaging each bucket's individual conversion percentage.
	measure 'Session Conversion Rate' = DIVIDE(SUM(FactSessionDepth[PurchasingSessions]), SUM(FactSessionDepth[TotalSessions]))
		formatString: 0.00%
		displayFolder: Funnel
		lineageTag: d86a30d4-da47-4b1b-b288-809c975e9cf5

	/// A range of how many events happened in a single browsing session (e.g. '1 event', '6-10 events'). Used to see how session depth relates to whether a purchase happens.
	column EventBucket
		dataType: string
		lineageTag: 8fc88180-490f-4802-8808-c4d81b9bbf01
		summarizeBy: none
		sourceColumn: EventBucket

		annotation SummarizationSetBy = Automatic

	/// Number of sessions falling into this event-count bucket.
	column TotalSessions
		dataType: int64
		formatString: 0
		lineageTag: 09dbf007-78d6-46f3-b2ea-cf922a519834
		summarizeBy: sum
		sourceColumn: TotalSessions

		annotation SummarizationSetBy = Automatic

	/// Of the sessions in this bucket, how many included a purchase.
	column PurchasingSessions
		dataType: int64
		formatString: 0
		lineageTag: b59b4323-6602-4b74-bb61-ff299a184079
		summarizeBy: sum
		sourceColumn: PurchasingSessions

		annotation SummarizationSetBy = Automatic

	/// This bucket's conversion rate. Read per-row only - use the 'Session Conversion Rate' measure for a correctly blended figure.
	column ConversionPct
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 651468ac-39ad-479a-a972-832732df83ac
		summarizeBy: none
		sourceColumn: ConversionPct

		annotation SummarizationSetBy = Automatic

	partition FactSessionDepth = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Jean-Yves TRAN\FOR_GITHUB\Data_Analyst_Projects\project2_ecommerce_behavior_analytics\dashboards\powerbi_source_data.xlsx"), null, true),
				    FactSessionDepth_Sheet = Source{[Item="FactSessionDepth",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(FactSessionDepth_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"EventBucket", type text}, {"TotalSessions", Int64.Type}, {"PurchasingSessions", Int64.Type}, {"ConversionPct", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

