table FactAnomalyFindings
	lineageTag: f0d5a552-37b9-4f8d-9161-1d68b44a2ff6

	column Finding
		dataType: string
		lineageTag: 00c021a0-3ca8-4057-a182-dab3123d3487
		summarizeBy: none
		sourceColumn: Finding

		annotation SummarizationSetBy = Automatic

	column Detail
		dataType: string
		lineageTag: 3f39d5c5-39c4-42d8-8ed0-3b70e9ec5a60
		summarizeBy: none
		sourceColumn: Detail

		annotation SummarizationSetBy = Automatic

	partition FactAnomalyFindings = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Jean-Yves TRAN\FOR_GITHUB\Data_Analyst_Projects\project2_ecommerce_behavior_analytics\dashboards\powerbi_source_data.xlsx"), null, true),
				    FactAnomalyFindings_Sheet = Source{[Item="FactAnomalyFindings",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(FactAnomalyFindings_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Finding", type text}, {"Detail", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

