table FactTopBrands
	lineageTag: 14ab2cbb-4a2b-4784-a4cd-b7f0133dc6f5

	column Brand
		dataType: string
		lineageTag: a69b34fd-e236-4118-9399-1aea377afbac
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Purchases
		dataType: int64
		formatString: 0
		lineageTag: 478fd042-ae5d-4377-b9e0-175e1f06cadf
		summarizeBy: sum
		sourceColumn: Purchases

		annotation SummarizationSetBy = Automatic

	column TotalRevenue
		dataType: int64
		formatString: 0
		lineageTag: d1f77856-a6af-45ff-9e1b-30747ac3108f
		summarizeBy: sum
		sourceColumn: TotalRevenue

		annotation SummarizationSetBy = Automatic

	column AvgPrice
		dataType: double
		lineageTag: 1f308250-a735-4982-bf7e-cc18d19d0048
		summarizeBy: sum
		sourceColumn: AvgPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CategoriesCount
		dataType: int64
		formatString: 0
		lineageTag: 24ff4a7c-4dd8-49a4-a7a2-9828e8ffbec8
		summarizeBy: sum
		sourceColumn: CategoriesCount

		annotation SummarizationSetBy = Automatic

	partition FactTopBrands = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Jean-Yves TRAN\FOR_GITHUB\Data_Analyst_Projects\project2_ecommerce_behavior_analytics\dashboards\powerbi_source_data.xlsx"), null, true),
				    FactTopBrands_Sheet = Source{[Item="FactTopBrands",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(FactTopBrands_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Brand", type text}, {"Purchases", Int64.Type}, {"TotalRevenue", Int64.Type}, {"AvgPrice", type number}, {"CategoriesCount", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

